[package]
name = "actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "^4"
jsonwebtoken = "8"
bcrypt = "0.12"
rusqlite = "0.25"
serde = { version = "^1", features = ["derive"] }
chrono = "0.4.38"
argon2 = "0.5.3"
dotenv = "0.15.0"
